### ISSUE TITLE
Object returned has key 'totaPages' instead of 'totalPages'

### ISSUE THREAD

**Issue by drewpereli** [NetanelBasal/paginate-array#1]
Pretty self explanatory. It seems to just be a typo.

**Comment by NetanelBasal** [comment]
Updated in version 2.0, thanks.

**Comment by djoos** [comment]
Hmmm, I've just installed 2.0.0 and seem to get the "totaPages" key only...
Thanks in advance for your feedback!

**Comment by NetanelBasal** [comment]
https://github.com/NetanelBasal/paginate-array/blob/master/src/paginate-array.js#L14

**Comment by djoos** [comment]
That's correct on GitHub, however when inspecting paginate-array@2.0.0 in node_modules:

``` paginate-array.js
  return {
    currentPage: currentPage,
    perPage: perPage,
    total: collection.length,
    totaPages: Math.ceil(collection.length / perPage),
    data: paginatedItems
  };
```

[EDIT]
Ok, got it! ...must have pulled in a stale previous version: local was incorrect, however https://registry.npmjs.org/paginate-array/-/paginate-array-2.0.0.tgz is as expected.

Fixed now, thanks for your quick response!

**Comment by djoos** [comment]
Actually: check out https://registry.npmjs.org/paginate-array/-/paginate-array-2.0.0.tgz. lib and src mismatch. I make use of require, so lib is returning totaPages...

**Comment by NetanelBasal** [comment]
try 2.1.0

**Comment by djoos** [comment]
Bingo - thanks!
